// Project-type registry → Strategy template management domain. A platform admin
// (Settings › Project-type registry › Strategy) authors reusable strategy
// TEMPLATES: each template is an ordered list of PHASES, and each phase configures
// the mandatory input documents it consumes and the output documents the AI
// generates (each output carries the prompt that drives its generation).
//
// Two ownership scopes: `system` templates ship with the platform and are
// read-only (duplicate to customise); `tenant` templates are authored here and
// fully editable. Mirrors the strategy module's mixed-RLS config schema so the
// shapes line up when the live backend is wired (the backend conforms to this
// contract).

import type { UseFormReturnType } from '@mantine/form'

/** Whether a template ships with the platform (read-only) or was authored by a tenant. */
export type TemplateScope = 'system' | 'tenant'

/**
 * The curated set of document types a doc slot can be tagged with. Multi-select
 * from this fixed list (no free entry) — keeps the catalogue tidy and the
 * generation pipeline predictable. Extend here when a new format is supported.
 */
export const DOC_TYPES = [
  'PDF',
  'Word',
  'Markdown',
  'Spreadsheet',
  'Presentation',
  'Diagram',
  'Image',
  'Other',
] as const

export type DocType = (typeof DOC_TYPES)[number]

/** Mantine Select data for the doc-type MultiSelect (value === label for the fixed list). */
export const DOC_TYPE_OPTIONS = DOC_TYPES.map((t) => ({ value: t, label: t }))

/** A mandatory/optional input document a phase consumes (uploaded by the user). */
export interface InputDocSlot {
  /** Client-stable id (for list keys + reorder); server assigns its own on persist. */
  id: string
  name: string
  /** Whether the phase cannot be generated until this document is provided. */
  mandatory: boolean
  /** Accepted document types (multi-select, fixed list). */
  documentTypes: DocType[]
}

/** An output document a phase produces — generated by the AI from the prompt. */
export interface OutputDocSlot {
  id: string
  name: string
  /** Output document types (multi-select, fixed list). */
  documentTypes: DocType[]
  /** The user-authored instruction the AI uses to generate this document. */
  prompt: string
}

/** One phase in a strategy template — an open-named stage with its doc config. */
export interface StrategyPhase {
  id: string
  /** Free-text phase name (e.g. "Roadmap", "Governance Framework"). */
  name: string
  description: string
  /** A mandatory phase must be completed for the strategy to be signed off. */
  mandatory: boolean
  inputs: InputDocSlot[]
  outputs: OutputDocSlot[]
}

/** A reusable strategy template: an ordered set of configured phases. */
export interface StrategyTemplate {
  id: number
  name: string
  description: string
  scope: TemplateScope
  phases: StrategyPhase[]
  /** Display name of the author ("System" for platform-shipped templates). */
  createdBy: string
  createdAt: string
  updatedBy: string
  updatedAt: string
}

// ── Editor draft shapes (what the form mutates; server fields stripped) ───────

// NOTE: the draft shapes are `type` aliases (not `interface`) on purpose — only
// type aliases get an implicit index signature, which mantine-form-yup-resolver
// requires (its resolver is typed `(values: Record<string, unknown>) => FormErrors`).
export type DocSlotDraft = {
  id: string
  name: string
  mandatory?: boolean
  documentTypes: DocType[]
  prompt?: string
}

export type PhaseDraft = {
  id: string
  name: string
  description: string
  mandatory: boolean
  inputs: DocSlotDraft[]
  outputs: DocSlotDraft[]
}

export type TemplateDraft = {
  name: string
  description: string
  phases: PhaseDraft[]
}

/**
 * The `useForm` return type for the template draft, shared by the editor and its
 * child field components. `TransformedValues`/`Rules` are left open (`any`) so a
 * form created with a `validate` resolver still assigns to this prop type — the
 * children only touch value-level helpers (getInputProps / get/insert/removeListItem),
 * none of which depend on those generics. `getValues()` still returns TemplateDraft.
 */
export type TemplateForm = UseFormReturnType<TemplateDraft, Record<string, unknown>>

/** Payload sent to create/update a tenant template (server derives author + scope). */
export interface SaveTemplateInput {
  /** Present on update; omitted on create. */
  id?: number
  draft: TemplateDraft
}

// ── Raw API shapes (mapped to the UI types above at the service boundary) ─────

/** Standard API envelope — every response wraps its payload in `result`. */
export interface ApiEnvelope<T> {
  result: T
  errors?: unknown
}

export interface IStrategyTemplate {
  id: number
  name: string
  description: string
  scope: TemplateScope
  phases: StrategyPhase[]
  createdBy?: string
  createdAt?: string
  updatedBy?: string
  updatedAt?: string
}

export interface IStrategyTemplatesResponse {
  templates: IStrategyTemplate[]
}
