import type { Project, ProjectType } from '@wispr/projects'
import { ProjectStatus } from '@wispr/projects'

// Project-entity types live in @wispr/projects (shared by host + workspace);
// re-exported so existing `from '../types'` imports keep working.
export type { Project, ProjectType }
export { ProjectStatus }

export type Phase =
  | 'discovery'
  | 'planning'
  | 'features'
  | 'implementation'
  | 'test'

/** Per-phase status as shown in phase navigation (rail / dropdown). */
export type PhaseStepStatus = 'active' | 'done' | 'available' | 'locked'

export type Priority = 'high' | 'medium' | 'low'
export type Complexity = 'xs' | 's' | 'm' | 'l' | 'xl'
export type StoryStatus = 'draft' | 'ready' | 'in-progress' | 'done' | 'closed'
export type TestStatus = 'pending' | 'pass' | 'fail'
export type TestType = 'unit' | 'integration' | 'e2e' | 'edge'
export type KBSectionId =
  | 'business-requirements'
  | 'problem-statements'
  | 'proposed-solutions'
  | 'architectural-notes'
  | 'tech-stack'
  | 'timeline'
  | 'stakeholders'
  | 'open-questions'
  | 'other-notes'

export interface User {
  id: string
  name: string
  email: string
  avatar?: string
  role: 'pm' | 'ba' | 'developer' | 'admin' | 'qa'
}

/** Normalised identity derived from the OIDC profile (no tokens). */
export interface AuthUser {
  id: string
  name: string
  email: string
}


export interface KBSection {
  id: KBSectionId
  label: string
  description: string
  notes: KBNote[]
  generatedAt?: string
  sourceFiles?: string[]
}

export interface KBNote {
  id: string
  sectionId: KBSectionId
  title: string
  description: string
  content: string
  generatedAt: string
  sourceFile?: string
  /** Versioning/supersedence (ADR-0015). Absent ⇒ treat as active. */
  status?: 'active' | 'superseded'
  generation?: number
  /** When superseded: why this note is no longer valid. */
  supersededReason?: string
  /** On a note: what changed vs the note it supersedes (better/worse). */
  changeSummary?: string
  supersededBy?: string
  /** Bumps only when the note's content materially changes — drives impact dedupe. */
  revision?: number
}

/** The latest generation's impact analysis (ADR-0015). */
export interface KbImpact {
  generation: number
  summary: string
  gaps: string
  createdAt?: string
}

export interface KnowledgeBase {
  projectId: string
  sections: KBSection[]
  lastGeneratedAt?: string
  sourceFileCount: number
  isComplete: boolean
  /** Current generation number (increments per generate-kb run). */
  generation?: number
  /** Latest-run impact analysis (what changed + gaps). */
  impact?: KbImpact | null
}

export interface UploadedFile {
  id: string
  name: string
  type: string
  size: number
  status: 'uploading' | 'processing' | 'ready' | 'error'
  uploadedAt: string
  url?: string // download URL (in-session object URL for mock; server URL when wired)
}

export interface AnalysisStep {
  id: string
  label: string
  status: 'pending' | 'running' | 'done' | 'error'
  estimatedSeconds?: number
}

export type FeatureStatus =
  | 'proposed'
  | 'under-review'
  | 'in-progress'
  | 'approved'
  | 'deferred'
  | 'rejected'

export interface Feature {
  id: string
  projectId: string
  title: string
  description: string
  priority: Priority
  complexity: Complexity
  /** Detailed, scannable functional requirements for this feature/module. */
  functionalRequirements: string[]
  /** Non-functional requirements — performance, security, accessibility, etc. */
  nonFunctionalRequirements: string[]
  /** True when the feature originated from AI generation (vs. manually added). */
  aiGenerated: boolean
  status: FeatureStatus
  order: number
  /**
   * Feature slugs (F-001…) this feature depends on (ADR-0026) — generated by the planning AI so
   * the working list can be shown in build order. Optional; absent on older plans (falls back to
   * dependencies derived from story links).
   */
  dependencies?: string[]
  storiesCount: number
  readyStoriesCount: number
  createdAt: string
  /** Soft-delete / supersede. Archived items stay as AI context but leave the lists. */
  archived?: boolean
  /** The revision that replaced this one (set when superseded via regenerate). */
  supersededById?: string
  /** Revision number; treat undefined as 1. Bumps on regenerate / material edit. */
  revision?: number
  /** Set by an "approve" review action — the feature is flagged as needing rework. */
  needsUpdate?: boolean
}

/**
 * A candidate feature the AI proposes in the Planning suggestions tray. The user
 * reviews each and either adds it to the feature list or dismisses it. Distinct
 * from `Feature` because it carries a `rationale` and has no list-level state
 * (order/status/story counts) until it is accepted into the plan.
 */
export interface SuggestedFeature {
  id: string
  title: string
  description: string
  priority: Priority
  complexity: Complexity
  functionalRequirements: string[]
  nonFunctionalRequirements: string[]
  /** Why the AI is proposing this feature — shown to help the user decide. */
  rationale: string
}

/**
 * The Planning output for a project: the working feature list plus the AI
 * suggestions tray. `null` (not this shape) means planning has not been
 * generated yet. `isThinKb` flags a Knowledge Base with fewer than 3 populated
 * sections so the UI can warn that results may be limited.
 */
export interface PlanningPlan {
  projectId: string
  features: Feature[]
  suggestions: SuggestedFeature[]
  generatedAt: string
  isThinKb: boolean
}

/** A structured Gherkin acceptance-criterion scenario (ADR-0033). */
export interface GherkinCriterion {
  /** happy-path | field-validation | cross-field-validation | exception | alternate-path */
  type: string
  title: string
  given: string
  when: string
  then: string
}

/** A story's user-journey (ADR-0033). */
export interface NavigationFlow {
  entryPoint: string
  happyPath: string[]
  alternatePaths: string[]
  exceptionPaths: string[]
}

/** A UI element in a story's screen inventory (ADR-0033). */
export interface StoryComponent {
  name: string
  type: string
  defaultState: string
  editable: boolean
  notes: string
}

/** A field-level validation rule for a story (ADR-0033). min/max are strings. */
export interface ValidationRule {
  field: string
  dataType: string
  required: boolean
  min: string
  max: string
  format: string
  errorMessage: string
  /** real-time | on-blur | on-submit */
  validationTiming: string
  serverSideRule: string
}

export interface Story {
  id: string
  featureId: string
  projectId: string
  title: string
  /** Free-text elaboration beyond the as-a/I-want/so-that statement. */
  description: string
  asA: string
  iWant: string
  soThat: string
  /** Structured Gherkin acceptance criteria (ADR-0033). */
  acceptanceCriteria: GherkinCriterion[]
  /** Enterprise-grade story detail (ADR-0033). */
  background?: string
  epic?: string
  version?: string
  assumptions?: string[]
  navigationFlow?: NavigationFlow | null
  components?: StoryComponent[]
  validationRules?: ValidationRule[]
  /** The business need/value this story satisfies (AI-generated; ADR-0017). */
  businessRequirements?: string[]
  /** What the system must do for this story (AI-generated; ADR-0017). */
  functionalRequirements?: string[]
  /** Quality attributes — security, performance, compliance… (AI-generated; ADR-0017). */
  nonFunctionalRequirements?: string[]
  /** Explicitly not covered by this story (AI-generated; ADR-0017). */
  outOfScope?: string[]
  /** Data/database requirements the story implies (AI-generated; ADR-0017). */
  dataRequirements?: string[]
  /** What must be true/done before this story can start (AI-generated; ADR-0017). */
  blockers?: string[]
  /** What could go wrong or add uncertainty (AI-generated; ADR-0017). */
  risks?: string[]
  effort: 1 | 2 | 3 | 5 | 8
  status: StoryStatus
  assignee?: string
  dependencies: string[]
  impactedStories: string[]
  impactSummary?: string
  impactDismissed: boolean
  tags: string[]
  createdAt: string
  /** Soft-delete / supersede. Archived items stay as AI context but leave the lists. */
  archived?: boolean
  /** The revision that replaced this one (set when superseded via regenerate). */
  supersededById?: string
  /** Revision number; treat undefined as 1. Bumps on regenerate / material edit. */
  revision?: number
  /** Set by an "approve" review action — the story is flagged as needing rework. */
  needsUpdate?: boolean

  // Dependency-ordered planning + guardrails (ADR-0026) — computed server-side over the active set.
  /** Topological rank — dependencies sort before dependents (0 = no in-set deps). */
  order?: number
  /** True when status is 'ready' and every dependency is 'done' — startable now. */
  developable?: boolean
  /** Dependency slugs not yet 'done' — these block starting development. */
  blockedBy?: string[]
  /** True when every dependency is at least 'ready' — this story may be marked ready. */
  canMarkReady?: boolean
}

/** AI dependency analysis (ADR-0026) — advisory suggestions the user reviews. */
export interface DependencySuggestion {
  story: string
  dependsOn: string
  reason: string
}

export interface DependencyAnalysis {
  suggestions: DependencySuggestion[]
  cycles: string[][]
  order: string[]
}

export interface TechStackItem {
  category: string
  value: string
  aiSuggested: boolean
}

export interface TechStack {
  projectId: string
  items: TechStackItem[]
  lockedAt?: string
}

export interface GeneratedFile {
  filename: string
  language: string
  content: string
}

export interface GeneratedCode {
  storyId: string
  files: GeneratedFile[]
  generatedAt: string
}

export interface RepoFile {
  name: string
  path: string
  type: 'file' | 'directory'
  children?: RepoFile[]
}

export type RepoProvider = 'github' | 'bitbucket' | 'azure-devops' | 'gitlab'

export interface RepoConnection {
  projectId: string
  repoName: string
  branch: string
  provider: RepoProvider
  connectedAt: string
  fileTree: RepoFile[]
  /** Org / workspace the repo lives under (from the setup wizard). */
  organisation?: string
  /** Monorepo flag + the frontend / backend sub-paths when set. */
  isMonorepo?: boolean
  frontendPath?: string
  backendPath?: string
}

/** The Implementation workspace sections (the sidebar menu, extensible). */
export type ImplementationSectionId =
  | 'stories'
  | 'frontend'
  | 'backend'
  | 'database'
  | 'design'
  | 'log'

/** Per-section setup completeness, drives the sidebar status dots. */
export type SetupStatus = 'complete' | 'partial' | 'untouched'

/** Frontend / Backend workspace modes. */
export type DevelopMode = 'develop' | 'code' | 'preview'

/** Category of an external design reference link — drives its label and icon. */
export type DesignReferenceCategory =
  | 'design-system'
  | 'brand'
  | 'storybook'
  | 'documentation'
  | 'other'

/** A user-added external reference the AI and developers can consult. */
export interface DesignReferenceLink {
  id: string
  label: string
  url: string
  category: DesignReferenceCategory
}

/** Design-system assets gathered for a project (references, Figma, tokens, AI instructions). */
export interface DesignAssets {
  projectId: string
  figmaUrl?: string
  hasFigmaToken: boolean
  /** Parsed design tokens (raw JSON object) when uploaded/pasted. */
  tokens?: Record<string, unknown>
  uploads: UploadedFile[]
  /** External reference links (design system, brand guide, Storybook, docs, …). */
  referenceLinks?: DesignReferenceLink[]
  /** Free-form design notes embedded into AI instructions. */
  notes?: string
  aiInstructionsFormat?: 'claude' | 'cursor' | 'copilot'
  aiInstructionsContent?: string
}

export interface SchemaColumn {
  name: string
  type: string
  nullable: boolean
  isPrimary: boolean
}

export interface SchemaTable {
  name: string
  columns: SchemaColumn[]
}

export interface DbSchema {
  projectId: string
  tables: SchemaTable[]
  generatedAt: string
  sql: string
  prisma: string
}

/** Tracks whether the first-time setup wizard has been dismissed for a project. */
export type ScaffoldStatus = 'not-started' | 'in-progress' | 'ready' | 'failed'

export interface ImplementationSetup {
  projectId: string
  wizardDismissed: boolean
  /** Initial scaffold state — story code-gen into the repo is gated on 'ready' (ADR-0025). */
  scaffoldStatus: ScaffoldStatus
  scaffoldBranch?: string | null
  scaffoldedAt?: string | null
}

export interface TestCase {
  id: string
  storyId: string
  title: string
  type: TestType
  steps: string[]
  expectedResult: string
  status: TestStatus
  fromImplementation: boolean
  createdAt: string
}

/**
 * Cross-phase change-impact system. When an upstream artifact (KB note, feature)
 * changes, the engine raises `ChangeImpactAlert`s against the downstream
 * artifacts that may need review — the platform's "everything is connected"
 * guarantee. Alerts are never deleted; they resolve to a terminal status.
 */
export type ImpactPhase = 'discovery' | 'planning' | 'features'
export type ImpactKind = 'kb-note' | 'feature' | 'story'
export type ImpactChangeType =
  | 'edited'
  | 'enhanced'
  | 'regenerated'
  | 'archived'
  | 'status-changed'
  | 'added'
export type ImpactSeverity = 'critical' | 'warning' | 'info'
export type ImpactStatus = 'open' | 'acknowledged' | 'approved' | 'rejected'
export type ReviewAction = 'approve' | 'reject' | 'acknowledge' | 'regenerate'

/** Points at an artifact in a phase (the thing that changed, or the thing impacted). */
export interface ImpactRef {
  phase: ImpactPhase
  kind: ImpactKind
  refId: string
  label: string
}

export interface ImpactResolution {
  action: ReviewAction
  decidedAt: string
  note?: string
}

export interface ChangeImpactAlert {
  id: string
  projectId: string
  createdAt: string
  source: ImpactRef & { changeType: ImpactChangeType }
  /** The source artifact's revision that produced this alert — dedupe + no-resurrect key. */
  sourceRevision: number
  target: ImpactRef
  severity: ImpactSeverity
  /** Markdown rationale explaining the impact (rendered read-only). */
  rationale: string
  suggestedAction: ReviewAction
  status: ImpactStatus
  resolution?: ImpactResolution
}

export type AuditEventType =
  | 'note-edited'
  | 'note-enhanced'
  | 'kb-regenerated'
  | 'feature-edited'
  | 'feature-archived'
  | 'plan-regenerated'
  | 'feature-status-changed'
  | 'story-edited'
  | 'story-archived'
  | 'stories-regenerated'
  | 'story-status-changed'
  | 'alert-approved'
  | 'alert-rejected'
  | 'alert-acknowledged'
  | 'alert-regenerated'

/** Append-only record of every material change and review decision (traceability). */
export interface AuditEntry {
  id: string
  projectId: string
  at: string
  type: AuditEventType
  refId: string
  summary: string
  alertId?: string
}

/**
 * Minimal Web Speech API surface. The browser ships this at runtime but it is
 * absent from TypeScript's default DOM lib, so we declare only the members the
 * dictation feature uses — enough to stay fully typed without pulling in a
 * dependency. See `useDictation`.
 */
export interface SpeechRecognitionAlternative {
  readonly transcript: string
}

export interface SpeechRecognitionResult {
  readonly isFinal: boolean
  readonly length: number
  item(index: number): SpeechRecognitionAlternative
  [index: number]: SpeechRecognitionAlternative
}

export interface SpeechRecognitionResultList {
  readonly length: number
  item(index: number): SpeechRecognitionResult
  [index: number]: SpeechRecognitionResult
}

export interface SpeechRecognitionEvent extends Event {
  readonly resultIndex: number
  readonly results: SpeechRecognitionResultList
}

export interface SpeechRecognitionErrorEvent extends Event {
  readonly error: string
  readonly message: string
}

export interface SpeechRecognition extends EventTarget {
  lang: string
  continuous: boolean
  interimResults: boolean
  start(): void
  stop(): void
  abort(): void
  onresult: ((event: SpeechRecognitionEvent) => void) | null
  onerror: ((event: SpeechRecognitionErrorEvent) => void) | null
  onend: ((event: Event) => void) | null
}

export interface SpeechRecognitionConstructor {
  new (): SpeechRecognition
}

declare global {
  interface Window {
    SpeechRecognition?: SpeechRecognitionConstructor
    webkitSpeechRecognition?: SpeechRecognitionConstructor
  }
}
