import type { GeneratedCode, GeneratedFile, Story, TechStackItem } from '../../../../types'
import { languageOf, toComponentName } from './helpers'
import { criterionText } from '../../../../utility/story'

/** Looks up a stack value by category, with a sensible fallback. */
function stackValue(items: TechStackItem[], category: string, fallback: string): string {
  return items.find((i) => i.category === category)?.value ?? fallback
}

/**
 * Mock AI code generation for a story. Produces a small, realistic file set —
 * a UI component, an API route, and a unit-test stub — wired to the story's
 * acceptance criteria and the project's configured tech stack. The test stub is
 * deliberately included so the Test phase can surface it without regeneration
 * (requirements §9.1).
 */
export function generateMockCode(story: Story, stack: TechStackItem[], generatedAt: string): GeneratedCode {
  const name = toComponentName(story.title)
  const uiLib = stackValue(stack, 'UI Library', 'Mantine')
  const backend = stackValue(stack, 'Backend', 'Node.js + Express')
  const criteria = story.acceptanceCriteria.length
    ? story.acceptanceCriteria.map(criterionText)
    : ['Renders without error', 'Handles the primary user action', 'Surfaces loading and error states']

  const componentFile = makeComponentFile(name, uiLib, story)
  const routeFile = makeRouteFile(backend, story)
  const testFile = makeTestFile(name, criteria, story.id)

  const files: GeneratedFile[] = [componentFile, routeFile, testFile]
  return { storyId: story.id, files, generatedAt }
}

function makeComponentFile(name: string, uiLib: string, story: Story): GeneratedFile {
  const filename = `src/features/${name}/${name}.tsx`
  const content = [
    "import { useState } from 'react'",
    "import { Stack, Title, Text, Button, Loader } from '@mantine/core'",
    '',
    '/**',
    ` * ${name}`,
    ` * ${story.id}: As a ${story.asA || 'user'}, I want ${story.iWant || story.title}, so that ${story.soThat || 'the goal is met'}.`,
    ` * Built with ${uiLib}. Generated by WISPR from the approved user story.`,
    ' */',
    `export function ${name}() {`,
    '  const [loading, setLoading] = useState(false)',
    '  const [error, setError] = useState<string | null>(null)',
    '',
    '  async function handleAction() {',
    '    setLoading(true)',
    '    setError(null)',
    '    try {',
    `      await fetch('/api/${story.id.toLowerCase()}', { method: 'POST' })`,
    '    } catch {',
    "      setError('Something went wrong. Please try again.')",
    '    } finally {',
    '      setLoading(false)',
    '    }',
    '  }',
    '',
    '  return (',
    '    <Stack gap="md">',
    `      <Title order={3}>${story.title}</Title>`,
    error_line(),
    '      <Button onClick={handleAction} loading={loading}>',
    '        Continue',
    '      </Button>',
    '    </Stack>',
    '  )',
    '}',
    '',
  ].join('\n')
  return { filename, language: languageOf(filename), content }
}

// Kept separate to avoid a brittle nested-quote line in the array above.
function error_line(): string {
  return '      {error && <Text c="red" size="sm">{error}</Text>}'
}

function makeRouteFile(backend: string, story: Story): GeneratedFile {
  const route = story.id.toLowerCase()
  const filename = `src/server/routes/${route}.ts`
  const content = [
    "import { Router, type Request, type Response } from 'express'",
    '',
    `// ${backend} route backing "${story.title}" (${story.id}).`,
    'export const router = Router()',
    '',
    `router.post('/api/${route}', async (req: Request, res: Response) => {`,
    '  try {',
    '    // TODO(impl): validate the request body against the story acceptance criteria.',
    '    const result = await handle(req.body)',
    '    res.status(200).json(result)',
    '  } catch (err) {',
    "    res.status(500).json({ error: 'Internal error' })",
    '  }',
    '})',
    '',
    'async function handle(input: unknown) {',
    '  // Placeholder business logic for the generated story.',
    '  return { ok: true, input }',
    '}',
    '',
  ].join('\n')
  return { filename, language: languageOf(filename), content }
}

function makeTestFile(name: string, criteria: string[], storyId: string): GeneratedFile {
  const filename = `src/features/${name}/${name}.test.tsx`
  const cases = criteria
    .map((c, i) => [`  it('${escapeQuotes(c)}', () => {`, `    // TODO(impl): assert acceptance criterion ${i + 1}.`, '    expect(true).toBe(true)', '  })'].join('\n'))
    .join('\n\n')
  const content = [
    "import { describe, it, expect } from 'vitest'",
    '',
    `// Unit test stub for ${storyId} — one case per acceptance criterion.`,
    `describe('${name}', () => {`,
    cases,
    '})',
    '',
  ].join('\n')
  return { filename, language: languageOf(filename), content }
}

function escapeQuotes(s: string): string {
  return s.replace(/'/g, "\\'")
}
