import type { RepoConnection, TechStackItem, DesignReferenceLink } from '../models/model'

export type AiInstructionFormat = 'claude' | 'cursor' | 'copilot'

/** The file an AI-instruction format writes to at the repo root. */
export const AI_FORMAT_FILENAME: Record<AiInstructionFormat, string> = {
  claude: 'CLAUDE.md',
  cursor: '.cursorrules',
  copilot: '.github/copilot-instructions.md',
}

export interface Convention {
  label: string
  value: string
}

interface BuildAiInstructionsParams {
  projectName: string
  techStack: TechStackItem[]
  repo: RepoConnection | null
  designNotes?: string
  referenceLinks?: DesignReferenceLink[]
  conventions: Convention[]
  format: AiInstructionFormat
}

/**
 * Mock generation of the AI instruction file the platform would write to the
 * repo root. Assembles tech stack + repo + conventions + design notes into a
 * Markdown document the user can preview and copy. Realistic placeholder for the
 * real generation endpoint.
 */
export function buildAiInstructions({
  projectName,
  techStack,
  repo,
  designNotes,
  referenceLinks,
  conventions,
  format,
}: BuildAiInstructionsParams): string {
  const stackLines = techStack.length
    ? techStack.map((i) => `- **${i.category}:** ${i.value}`).join('\n')
    : '- _(not configured yet)_'
  const conventionLines = conventions.length
    ? conventions.map((c) => `- **${c.label}:** ${c.value}`).join('\n')
    : '- _(none added)_'
  const repoLine = repo
    ? `${repo.provider} · \`${repo.repoName}\` · branch \`${repo.branch}\`${repo.isMonorepo ? ' · monorepo' : ''}`
    : '_(not connected)_'
  const referenceLines = referenceLinks && referenceLinks.length
    ? referenceLinks.map((r) => `- **${r.label}:** ${r.url}`).join('\n')
    : '- _(none added)_'
  const heading =
    format === 'cursor'
      ? '# Cursor Rules'
      : format === 'copilot'
        ? '# GitHub Copilot Instructions'
        : `# ${projectName} — AI Instructions`

  return [
    heading,
    '',
    'Generated by WISPR from the Implementation setup. Every generated file MUST follow the',
    'tech stack, conventions, and design notes below.',
    '',
    '## Tech stack',
    stackLines,
    '',
    '## Repository',
    `- ${repoLine}`,
    '',
    '## Conventions',
    conventionLines,
    '',
    '## References',
    referenceLines,
    '',
    '## Design notes',
    designNotes?.trim() ? designNotes.trim() : '- _(none provided)_',
    '',
  ].join('\n')
}
