import { zipSync, strToU8 } from 'fflate'
import type { GeneratedFile } from '../../../../types'

/**
 * Bundle generated files into a .zip that runs locally — alongside a minimal scaffold (package.json
 * / tsconfig / vite / .csproj / Program.cs + README) chosen from the files' stack (ADR-0022). The
 * generated files are a starting point; the README explains the one-command run. Scaffold files are
 * only added when absent, so a real repo's own config is never overwritten.
 */
type Stack = 'react' | 'dotnet' | 'node' | 'unknown'

function detectStack(files: GeneratedFile[]): Stack {
  const names = files.map((f) => f.filename.toLowerCase())
  if (names.some((n) => n.endsWith('.cs'))) return 'dotnet'
  if (names.some((n) => n.endsWith('.tsx') || n.endsWith('.jsx'))) return 'react'
  if (names.some((n) => n.endsWith('.ts') || n.endsWith('.js'))) return 'node'
  return 'unknown'
}

function reactScaffold(name: string): Record<string, string> {
  return {
    'package.json': JSON.stringify(
      {
        name,
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'tsc -b && vite build', preview: 'vite preview', test: 'vitest run' },
        dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
        devDependencies: {
          '@testing-library/jest-dom': '^6.4.0', '@testing-library/react': '^16.0.0',
          '@types/react': '^18.3.0', '@types/react-dom': '^18.3.0', '@vitejs/plugin-react': '^4.3.0',
          jsdom: '^24.0.0', typescript: '^5.5.0', vite: '^5.4.0', vitest: '^2.0.0',
        },
      },
      null, 2,
    ),
    'vite.config.ts':
      `import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\n` +
      `export default defineConfig({\n  plugins: [react()],\n  test: { environment: 'jsdom', globals: true, setupFiles: './vitest.setup.ts' },\n})\n`,
    'vitest.setup.ts': `import '@testing-library/jest-dom'\n`,
    'tsconfig.json': JSON.stringify(
      { compilerOptions: { target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler', jsx: 'react-jsx', strict: true, esModuleInterop: true, skipLibCheck: true, types: ['vitest/globals'] }, include: ['src'] },
      null, 2,
    ),
    'index.html': `<!doctype html>\n<html><head><meta charset="UTF-8"/><title>${name}</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n`,
    'src/main.tsx':
      `import { StrictMode } from 'react'\nimport { createRoot } from 'react-dom/client'\n\n` +
      `// Wire your generated component(s) from ./components here, e.g.:\n` +
      `// import { Something } from './components/Something'\n\n` +
      `createRoot(document.getElementById('root')!).render(\n  <StrictMode>\n    <main style={{ padding: 24, fontFamily: 'system-ui' }}>\n      <h1>${name}</h1>\n      <p>Generated component(s) live under <code>src/components</code>. Import one above and render it.</p>\n    </main>\n  </StrictMode>,\n)\n`,
    'README.md':
      `# ${name}\n\nGenerated by WISPR (frontend). Run locally:\n\n\`\`\`bash\nnpm install\nnpm run dev     # start the app\nnpm run test    # run the generated tests\n\`\`\`\n\nGenerated files are under \`src/\`. Wire your component into \`src/main.tsx\`.\n`,
  }
}

function dotnetScaffold(name: string): Record<string, string> {
  const safe = name.replace(/[^A-Za-z0-9_.]/g, '') || 'Generated'
  return {
    [`${safe}.csproj`]:
      `<Project Sdk="Microsoft.NET.Sdk.Web">\n  <PropertyGroup>\n    <TargetFramework>net8.0</TargetFramework>\n    <Nullable>enable</Nullable>\n    <ImplicitUsings>enable</ImplicitUsings>\n  </PropertyGroup>\n</Project>\n`,
    'Program.cs':
      `var builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddControllers();\nvar app = builder.Build();\napp.MapControllers();\napp.Run();\n`,
    'README.md':
      `# ${name}\n\nGenerated by WISPR (backend, ASP.NET). Run locally:\n\n\`\`\`bash\ndotnet restore\ndotnet run      # start the API\ndotnet test     # if a test project is included\n\`\`\`\n\nControllers live under \`Controllers/\`.\n`,
  }
}

function nodeScaffold(name: string): Record<string, string> {
  return {
    'package.json': JSON.stringify(
      {
        name, private: true,
        scripts: { start: 'node src/index.js', test: 'jest' },
        dependencies: { express: '^4.19.2' },
        devDependencies: { jest: '^29.7.0', supertest: '^7.0.0' },
      },
      null, 2,
    ),
    'src/index.js':
      `const express = require('express');\nconst app = express();\napp.use(express.json());\n\n` +
      `// Wire your generated routers from ./routes here, e.g.:\n// app.use(require('./routes/<name>.routes'));\n\n` +
      `const port = process.env.PORT || 3000;\napp.listen(port, () => console.log('Listening on ' + port));\n\nmodule.exports = app;\n`,
    'README.md':
      `# ${name}\n\nGenerated by WISPR (backend, Node/Express). Run locally:\n\n\`\`\`bash\nnpm install\nnpm start       # start the API\nnpm test        # run the generated tests\n\`\`\`\n\nRoutes live under \`src/routes\`. Wire them into \`src/index.js\`.\n`,
  }
}

function scaffoldFor(stack: Stack, name: string): Record<string, string> {
  if (stack === 'react') return reactScaffold(name)
  if (stack === 'dotnet') return dotnetScaffold(name)
  if (stack === 'node') return nodeScaffold(name)
  return { 'README.md': `# ${name}\n\nGenerated by WISPR. Add these files to a project of the matching stack to run them.\n` }
}

/** Build + download a runnable project zip: scaffold (only for absent files) + generated files. */
export function downloadRunnableProject(name: string, files: GeneratedFile[]): void {
  const entries: Record<string, Uint8Array> = {}
  const generatedPaths = new Set(files.map((f) => f.filename.replace(/^\/+/, '')))

  // Scaffold first (skip anything the generated files already provide).
  for (const [path, content] of Object.entries(scaffoldFor(detectStack(files), name))) {
    if (!generatedPaths.has(path)) entries[path] = strToU8(content)
  }
  for (const file of files) {
    entries[file.filename.replace(/^\/+/, '')] = strToU8(file.content)
  }

  const zipped = zipSync(entries, { level: 6 })
  const blob = new Blob([zipped.slice()], { type: 'application/zip' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = name.endsWith('.zip') ? name : `${name}.zip`
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}
